language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
env:
  - FLASK_APP=run.py SECRET=testing_secret??? APP_SETTINGS=testing DATABASE_URL=postgresql:///maragi_test_db
# command to run tests
before_script:
  - psql -c 'create database maragi_test_db;' -U postgres
script:
  - nose2 -v
notifications:
  email: false