language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
# command to run tests
before_script:
  - psql -c 'create database maragi_tdd_test;' -U postgres
script:
  - pytest
notifications:
  email: false